Update README.md
Ece-Kahraman/Eventium pull request #1
Opened 2023-09-30 11:58 UTC by vIremAydin

2023-09-30 11:59 UTC, Ece-Kahraman commented on README.md
> +h.
napıyon

2023-09-30 11:59 UTC, vIremAydin commented on README.md
> +h.
iyidir canım

2023-09-30 12:01 UTC, Ece-Kahraman commented
sen sen

2023-09-30 12:02 UTC, Ece-Kahraman commented on README.md
> +h.
eyo

2023-09-30 12:02 UTC, Ece-Kahraman commented on README.md
> +h.
sil bunu

2023-09-30 13:21 UTC, merged

2024-03-16 19:39 UTC, Ece-Kahraman commented on README.md
> @@ -14,8 +14,11 @@ system reports like finding the most popular events in a month based on the numb
aaaa

2024-03-16 19:42 UTC, Ece-Kahraman commented on README.md
>  people who attended etc.
aaaa

2024-03-16 19:44 UTC, Ece-Kahraman commented on README.md
>  We have used HTML and CSS for the pages, PHP for connecting them to the database, and SQL for the database itself.
aaaa

2024-03-19 15:07 UTC, Ece-Kahraman commented on README.md
ISSUE (BLOCKING): change required

2024-03-19 22:52 UTC, Ece-Kahraman approved these changes
hello

2024-03-19 22:52 UTC, Ece-Kahraman commented on README.md
ISSUE (IF-MINOR): hello

2024-03-19 23:14 UTC, Ece-Kahraman approved these changes
hello

2024-03-19 23:14 UTC, Ece-Kahraman commented on README.md
ISSUE (IF-MINOR): hello

2024-03-19 23:47 UTC, Ece-Kahraman requested changes
hello

2024-03-19 23:47 UTC, Ece-Kahraman commented on README.md
>  We have used HTML and CSS for the pages, PHP for connecting them to the database, and SQL for the database itself.
THOUGHT (IF-MINOR): hello